name: CI build

on:
  pull_request_target:
    types: [closed]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Hello
        run: echo "Parent wf"
