name: Workflow One

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get timestamp
        run: |
          echo "TIMESTAMP=$(date -u +"%Y-%m-%d_%H-%M-%S")"
